version: '3.7'

services:

  node:
    container_name: nodeapp_api
    image: nodeapp_api
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "5000:5000"
    networks:
      - nodeapp_api-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    

networks:
  nodeapp_api-network:
    driver: bridge